version: '3.9'
services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedulink
    ports:
      - "3306:3306"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
